### ISSUE TITLE
Debian os dependancy 'git-core' no longer exists:- now 'git'

### ISSUE THREAD

**Issue by pvdbergen** [kogitoapp/puppet-gitea#10]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  yep
- Ruby:
- Distribution:  debian
- Module version:

## How to reproduce (e.g Puppet code you use)

any Debian puppet run

## What are you seeing

debian dependancy 'git-core' is depreciated
/data/os/Debian.yaml

## What behaviour did you expect instead

should be 'git'

## Output log

every run attempts to apply git-core:

puppet-agent[1676]: (/Stage[main]/Gitea::Packages/Package[git-core]/ensure) created (corrective)

Also  noticed we were getting a dependancy loop when using vcsrepo

Found 1 dependency cycle:
(Anchor[gitea::begin] => Class[Gitea::Packages] => Package[git-core] => Vcsrepo[/opt/gitea/custom] => Class[Gitea] => Anchor[gitea::begin])\nTry 
Failed to apply catalog: One or more resource dependency cycles detected in graph

## Any additional information you'd like to impart

online discussions imply that a package 'git' already existed and git-core was the alternative name. This name clash has since been resolved and 'git' is the correct name - git-core no longer exists.

**Comment by danielsreichenbach** [comment]
Thanks for reporting this. I have changed the module to install the git package for Debian based systems.

Regarding the cycle you are seeing with vcsrepo: this module creates the directory, and ensures it has suitable permissions and belongs to the gitea user. If the vcsrepo module touches any of these things, that would trigger a rerun. I would suggest to open a feature request with additional details how you use vcsrepo (I assume you clone your gitea customizations?). Will have a look at that and try to implement a better solution for you.

**Comment by pvdbergen** [comment]
Hi Daniel,

thanks for that.  Will see if it makes a difference to the other odd
behaviour we are seeing - it could just be a symptom of somthing else...
too many unknowns and not enough beer...  More experienced eyes are looking
at it...

**Comment by danielsreichenbach** [comment]
I'm suspecting that due to both the gitea module and vcsrepo having a `file` resource active for that, it leads to the cycle. Probably would be better to not create and manage the customization directory from the gitea module side at all :thinking: then just accept whatever gets passed.

**Comment by pvdbergen** [comment]
there are layers here, indeed.

we're using vcsrepo to import the customisations into /opt/gitea/custom -
but that overwrites stuff that gitea creates - so there is already a timing
dependancy there... gotta run vcsrepo first or it overwrites puppet-gitea
created stuff.

There are probably better ways to organise this, but that's what we've got
at the moment...

separation of the "theme" bits of customisation from the app.ini bits would
allow a cleaner use of vcsrepo, for example, but we are probably already at
overkill...

for now it's probably in the "just hurry up and get the next thing done"
bucket...
