### ISSUE TITLE
Make download location base configurable

### ISSUE THREAD

**Issue by kasimon** [kogitoapp/puppet-gitea#4]
For systems without direct access to the internet, being able to point the module to an internal mirror/reverse proxy would be very helpful.

**Comment by danielsreichenbach** [comment]
@kasimon we're adding support for custom mirror location this week. Thanks for reporting!

**Comment by danielsreichenbach** [comment]
@kasimon The change has been added to `master`, a new release tag is also incoming.

**Comment by kasimon** [comment]
@danielsreichenbach awesome, thanks!
